apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: NodePort
  selector:
    app: movie
  ports:
   - name: flask
     port: 31234
     protocol: TCP
     targetPort: 65432
     nodePort: 31234
   - name: nginx
     port: 32233
     protocol: TCP
     targetPort: 80
     nodePort: 32233
